# Generated by Django 5.0.6 on 2024-06-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(db_column='图片路径', default='', max_length=255)),
                ('product_code', models.CharField(db_column='货号', default='', max_length=765)),
                ('original_product_code', models.CharField(db_column='原始货号', default='', max_length=765)),
                ('style_code', models.CharField(db_column='款号', default='', max_length=765)),
                ('factory_code', models.CharField(db_column='工厂代码', default='', max_length=765)),
                ('factory_product_code', models.CharField(db_column='工厂货号', default='', max_length=765)),
                ('insole_material', models.CharField(db_column='现管家婆鞋垫材质', default='', max_length=765)),
                ('outsole_material', models.CharField(db_column='现管家婆大底材质', default='', max_length=765)),
                ('lining_material', models.CharField(db_column='现管家婆内里材质', default='', max_length=765)),
                ('upper_material', models.CharField(db_column='现管家婆鞋面材质', default='', max_length=765)),
                ('group', models.CharField(db_column='组别', default='', max_length=765)),
                ('platform', models.CharField(db_column='所属平台', default='', max_length=765)),
                ('cost', models.FloatField(db_column='成本', default=0.0)),
                ('product_name', models.CharField(db_column='品名', default='', max_length=765)),
                ('season_classification', models.CharField(db_column='季节分类', default='', max_length=765)),
                ('season', models.CharField(db_column='季节', default='', max_length=765)),
                ('category', models.CharField(db_column='三级分类', default='', max_length=765)),
                ('first_order_date', models.CharField(db_column='首单日期', default='', max_length=765)),
                ('vip_first_sale_date', models.CharField(db_column='唯品首次售卖时间', default='', max_length=765)),
                ('dew_first_sale_date', models.CharField(db_column='得物首次售卖时间', default='', max_length=765)),
                ('latest_status', models.CharField(db_column='最新上下线状态', default='', max_length=765)),
                ('original_status', models.CharField(db_column='原始货号上线状态', default='', max_length=765)),
            ],
        ),
    ]
