# Generated by Django 5.0.6 on 2024-06-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
